# Change these first
owner: scriptex # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
    - name: Atanas
      url: https://atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: Github
      url: https://github.com
    - name: ITCSS
      url: https://itcss.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: ITSCSS
      url: https://itscss.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: At the Wall
      url: https://at-the-wall.atanas.info
      icon: https://at-the-wall.atanas.info/favicons/favicon-196x196.png
    - name: SCSS Goodies
      url: https://scss-goodies.atanas.info
      icon: https://scss-goodies.atanas.info/assets/images/favicon.png
    - name: Github Insights
      url: https://github-insights.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: URL Shortener
      url: https://shortener.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: TypeScript Helpers
      url: https://ts-helpers.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: Animate Me
      url: https://animate-me.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: Material Snake
      url: https://snake.atanas.info
      icon: https://snake.atanas.info/assets/favicon-196x196.png
    - name: Material Tetris
      url: https://tetris.atanas.info
      icon: https://tetris.atanas.info/assets/favicon-196x196.png
    - name: React Carousel
      url: https://react-carousel.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: React Round Carousel
      url: https://react-round-carousel.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: SOD 64
      url: https://sod.bg
      icon: https://sod.bg/favicon-32x32.png
    - name: Social Header
      url: https://social-header.atanas.info
      icon: https://raw.githubusercontent.com/scriptex/social-header/master/src/favicon.svg
    - name: Kinetik
      url: https://kinetik.atanas.info
      icon: https://kinetik.vercel.app/favicon/favicon.ico
    - name: React SVG Donuts
      url: https://react-svg-donuts.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: Calendar Widget
      url: https://calendar-widget.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: React Accordion TS
      url: https://react-accordion-ts.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: '2048'
      url: https://2048.atanas.info
      icon: https://2048.atanas.info/favicons/favicon.ico
    - name: Gitlab Calendar
      url: https://gitlab-calendar.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: Dator
      url: https://dator.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: Socials
      url: https://socials.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: scriptex.github.io
      url: https://scriptex.js.org
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: No HTML
      url: https://no-html.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png
    - name: Intro Scroll
      url: https://intro-scroll.atanas.info
      icon: https://atanas.info/images/favicon/favicon-196x196.png

status-website:
    name: Uptime
    cname: scriptex.js.org/uptime
    theme: dark
    baseUrl: /uptime
    logoUrl: https://raw.githubusercontent.com/scriptex/atanas.info/master/static/images/favicon/favicon-196x196.png
    favicon: https://raw.githubusercontent.com/scriptex/atanas.info/master/static/images/favicon/favicon.ico
    introTitle: 'This is my open-source uptime monitor and status page, powered entirely by GitHub and **Upptime**.'
    introMessage: This is the status page for my open source projects.
    navbar:
        - title: Back
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
