# Change these first
owner: scriptex # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
    - name: Atanas
      url: https://atanas.info
    - name: Github
      url: https://github.com
    - name: ITCSS
      url: https://itcss.atanas.info
    - name: ITSCSS
      url: https://itscss.atanas.info
    - name: At the Wall
      url: https://at-the-wall.atanas.info
    - name: SCSS Goodies
      url: https://scss-goodies.atanas.info
    - name: Github Insights
      url: https://github-insights.atanas.info
    - name: URL Shortener
      url: https://atanas.ml
    - name: TypeScript Helpers
      url: https://ts-helpers.atanas.info
    - name: Animate Me
      url: https://animate-me.atanas.info
    - name: Material Snake
      url: https://snake.atanas.info
    - name: Material Tetris
      url: https://tetris.atanas.info
    - name: Interactive Resume (WIP)
      url: https://interactive-resume.atanas.info

status-website:
    baseUrl: /uptime
    logoUrl: https://raw.githubusercontent.com/scriptex/atanas.info/master/static/images/favicon/favicon-196x196.png
    name: Uptime
    introTitle: 'This is my open-source uptime monitor and status page, powered entirely by GitHub and **Upptime**.'
    introMessage: This is the status page for my open source projects.
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
